### ISSUE TITLE
SAM validation error - No real operator in CIGAR

### ISSUE THREAD

**Issue by ThomasTaus** [magicDGS/ReadTools#35]
I used ReadTools v.0.2.2.r_4831abfbac to add read groups to a BAM-file and got the following error message:

```
SAM validation error: ERROR: Read name E00300:175:H3LYTALXX:6:1103:27813:5546#ACAGTGAT, No real operator (M|I|D|N) in CIGAR
```

This is the respective read pair:

```
E00300:175:H3LYTALXX:6:1103:27813:5546#ACAGTGAT 99      2L      1       70      150S    =       1       129     TTTTTTCGGTTCTTGACTGGGGCGGAGCGTGAACGCTCAGCTCTGTTTTCTCGGGAAAAAATACAAGCGCGAACTCCGCGTCGTGTTAAAGACATATATATTTTTTTAATCTCATTGATCTTTTTTTGCTGTTCTTTGCTTGTGGTTCTT  AAFFFKKKKAKKKKKKFKKKKKKKKAKKKFKKKKKKAF7KKKKKFFKKKKFKKKKKKKFKKKKAKKKKKKK<AKKKKKFFKKKKKKKKAKKKKFAKKKKKKKKKKKKFAA<KK7FKKKKKKKKKAKKKKKKAFKKKKKKKFKKFF7<FKA  AM:i:8  AS:i:256        MD:Z:114        NM:i:0  PG:Z:novoalign.I        PQ:i:438        SM:i:8  UQ:i:256
E00300:175:H3LYTALXX:6:1103:27813:5546#ACAGTGAT 147     2L      1       70      21S129M =       1       -129    ACTGGGGCGGAGCGTGAACGCTCAGCTCTGTTTTCTCGGGAAAAAATACAAGCGCGAACTCCGCGTCGTGTTAAAGACATATATATTTTTTTAATCTCATTGATCTTTTTTTGCTGTTCTTTGCTTGTGGTTCTTTTAGGAATTAATTGG  <KFAKKKKKKKKKKKKKKKKKKKKKKKKKF<KKKKKKKKFKKKKKKKKKKKKKKKKFKKKKKKKKKKKKKKKKKKKKKFKFKKKKKKKKKKKKKFKKKKKKKKKKKKKKKKKKKFKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKFFFAA  MD:Z:129        PG:Z:novoalign.I        AM:i:8  NM:i:0  SM:i:70 PQ:i:438        UQ:i:166        AS:i:166
```

Thanks a lot for looking into this, Daniel.

Cheers,

Thomas

**Comment by magicDGS** [comment]
Thanks @ThomasTaus (I edited your comment for making it more readable). I think that this will be solved by providing an option for SAM validation¡, so I will have a look after refactoring (#32).

**Comment by magicDGS** [comment]
Hi @ThomasTaus, can you have a look if the last release solve this problem? Just run the same command line as you did before but including the option `--VALIDATION_STRINGENCY SILENT` to be sure.

If it is not solved, I think that this is an specific issue of the library to handle SAM/BAM files and I can't do much more. Actually I don't fully understand how a BAM file could contain a read completely soft-clipped (150S).

I close the issue because I tried to solve it as far as I could. Open a new issue if you find more bugs and thanks for reporting it.
