### ISSUE TITLE
Leave mapper info with DownloadDistmapResult

### ISSUE THREAD

**Issue by robmaz** [magicDGS/ReadTools#394]
It might be nice to leave one of the @PG lines to retain the
mapper command line.  There is the --noRemoveTaskProgramGroup
option, but the description sounds as if this would merge all
100+ @PG lines in?

**Comment by magicDGS** [comment]
The default behavior is to remove all `@PG` tags generated before downloading, because they aren't useful and it just generate a super-big header. There is some effort in the hts-specs to address the map-reduce style of processing (already tracked in https://github.com/magicDGS/ReadTools/issues/355).

The main problem will be merging properly the task `@PG` tags, because letting just one does not really tell anything about how was the real processing. In addition, the distmap pipeline could have more than one command per task; e.g., bwa aln + bwa sampe. Dropping all but one `@PG` does not sound safe, because it can drop information for other programs.

Several ideas to solve this in the meantime are:
* Add a `--distmap-command` argument, where the full distmap command line is added as a `@PG` instead of mergint the `@PG` lines. Nevertheless, for only-download jobs this might not be useful at all.
* Add an option for a custom `@PG`, which will allow to pass a distmap command, but also just the mapper arguments and the mapper name. I am not in favor of that, because it will allow also to provide no-sense `@PG`.
* Add several options for the distmap command that can be important for reproduce the call and track the origin of the file. For example, inputs, mapper and mapper arguments. This will be a powerful command line, but it will be kind of difficult to implement.

Let me know if you would like to have one of this features before there is a decision in the hts-spec repository (that will be added to ReadTools while addressing #355).

**Comment by robmaz** [comment]
There seem to be left-over PG:Z:xxxxx tags in the read records, though, that now point to a non-existing program group, leading to downstream errors: I just got

Exception in thread "main" htsjdk.samtools.SAMException: 1 program groups weren't processed. Do their PP ids point to existing PGs? 
@PG ID:MarkDuplicates PN:MarkDuplicates PP:novoalign

when trying to merge a readtools-downloaded bam in with some others (with picard MergeSamFiles). Actually it looks like picard MarkDuplicates created the invalid header, but the novoalign info must have come from the left-over tags in the reads, because there no such info in the header.

**Comment by robmaz** [comment]
As to the distmap pipeline, I think it is guaranteed that the same processing happens on all mappers. So, while "dropping all but one `@PG`" might not be safe, keeping the @PG headers from part-00000 and discarding all others should be safe enough.

**Comment by magicDGS** [comment]
I open a new issue for the bug with respect to the `P G`tag in record (#396), that will be fixed.

I agree that it is safe to discard all but one for distmap, but I have the following example with bwa (actually, one of the test in the repository):

```
@PG	ID:bwa	PN:bwa	VN:0.7.13-r1126	CL:execarch/bin/bwa mem -M Genome_Index_Archive/ref/reference.fa mapping_20161019T145707read1.fastq mapping_20161019T145707read2.fastq
@PG	ID:bwa.1	PN:bwa	VN:0.7.13-r1126	CL:execarch/bin/bwa mem -M Genome_Index_Archive/ref/reference.fa mapping_20161019T150333read1.fastq mapping_20161019T150333read2.fastq
```

Even if the first is kept, it is not really meaningful (at least the `CL` tag), and thus I think that it is not really useful for identifying to which task each record belongs to. I think that the proper way to go is to keep all the headers in the case that the purpose is identify the read to belong to a map-reduce task (that can help pointing to tasks that didn't complete properly, for example).

Another option (although it depends a lot on how the `@PG` look for the different mappers) is to keep only the `ID`, `PN` and `VN ` (maybe also the `DS`, although depends on how it is treated by the mappers), removing completely the `CL` and possibly the `PP`. Then, it will collapse the ones that are the same.

Although I am more in favor of waiting for the hts-specs to define a consistent way of handling map-reduce `@PG` to allow to keep the information for all; but if you think that it is really necessary, I can implement an advance option to keep the first PG without the `CL`...

**Comment by robmaz** [comment]
I think the solution for that will be to keep the attempt IDs out of the
command line, so that the command lines are in fact identical. For example,
here is the command line left by my current homemade mapping script:

@PG ID:novoalign PN:novoalign VN:V3.08.02 CL:novoalign -f reads1.fq
reads2.fq -F STDFQ -i 390,78 -r RANDOM -o SAM -d refseq.nix


Exactly the same in all parts.  I don't think we should expect that BAM
headers will help us debug dubious cluster problems ...


Anyway, I don't think this is a high-priority issue. But I think we are
seeing the three options: drop entirely, merge into one with a normalized
(or dropped) CL,

or keep separate, and I don't see what else could come out of the hts-specs
discussion. The only thing they could possibly do is add isomething like an
IN tag

to differentiate instances even with identical CLs, for a variation of
option 3. You currently support 1 and 3 already. I think that in practice
option 2 would be

the most useful, because it retains the important mapper info while
avoiding the bloat.

2018-01-31 16:30 GMT+01:00 Daniel Gómez-Sánchez <notifications@github.com>:

**Comment by magicDGS** [comment]
Merging PGs is not an easy task, because it also requires to set the PG tag correctly in the read after it. Anyway, I will look at it after fixing the bug with the read PGs with novoalign (and other mappers if they set it).

**Comment by magicDGS** [comment]
@robmaz - I think that `--noRemoveTaskProgramGroup ` solves the issue if the `CL` line is the same for all the BAM files (which will happen, if I'm not wrong, with next distmap version).

Closing in favor of better documentation for the option and use cases (see #427)
