### ISSUE TITLE
security concern with distmap download

### ISSUE THREAD

**Issue by robmaz** [magicDGS/ReadTools#412]
ReadTools DownloadDistmapResult currently requires to specify the hdfs server on the command line, which ends up in the `@PG` header. This lets a viewer of the bam infer that there is a Hadoop cluster running, the DNS name of the namenode, and which ports are probably open. As bams or their headers may be distributed outside the institute, this could be considered a security issue.

Possible solution: if an environment variable, .e.g., `HDFS_PREFIX`, is set, append whatever is specified as `--input` to it, which allows to hide or expose as much or as little  If `HDFS_PREFIX` is not set, query the configuration in `HADOOP_CONF_DIR` (if set) for the necessary info (if Java has on-board tools for XPath queries, this would be a one-liner) and interpret the `--input` argument as an absolute path in the hdfs.

**Comment by magicDGS** [comment]
As discussed in person, I don't think that this is a real security concern for ReadTools but for user configuration of HDFS clusters:

* Hadoop cluster URIs should be safe if the cluster configuration have credentials to access. The real security concern is to have open IP addresses accessible for outsiders without firewall, credentials or user-specific access. The security concern is on the user-side and how they configure their cluster.
* I don't like the idea of adding a self-made environmental variable (or java options) to handle things, because they are error prone if the user forgets to set them up or someone else set them in the `.bash_profile` or `.bashrc`. One clear example is the Hadoop configuration based on different environmental variables in different versions, that override each other.
* ReadTools should work with several kind of `java.nio.Path`, and at the moment HDFS and Google Cloud Storage (GCS) are bundled. Assuming that a tool will only work with HDFS is not something that is on the concept of an "universal toolkit". For example, if the Hadoop cluster is running in MapR, a custom classpath with a `mapr` implementation of `java.nio.FileSystemProvider` can be added and work out of the box to download the files. Hard-coding HDFS environmental variables and/or checks for hadoop configurations limit the usage of ReadTools to work only on hdfs configurations.
* Tools should work on the local filesystem for testing and because launching `java -jar` locally assumes running in local. If relative paths in hadoop is required, maybe the option is to run [hadoop jar](https://hadoop.apache.org/docs/r1.0.4/commands_manual.html#jar) instead. I know that this requires remove the Hadoop dependencies from the uber-jar, and that is work in progress.

The `@PG` header for the program that is running can be remove completely from the written header using `--addOutputSAMProgramRecord false`. Another option is to re-header the file using samtools or picard, removing the `--input` from the `CL` or other sensitive information.

I will add a `wontfix` label to this issue, because I think that there is not going to be any solution from the ReadTools side. If more users ask for this and there is a concern for clusters with credentials and security setups, I will rethink about the possible solution; otherwise, this is a Institute-related issue, and it requires to work on the security of our Hadoop cluster.

**Comment by magicDGS** [comment]
Actually, I also think that the problem can be solved by using the `--arguments_file` argument: this is a file containing the arguments (for example, `--input ${HDFS_FILE} --output ${OUTPUT}`), and I think that it is not expanded when printing the command line.

I can't remember exactly the format of the file, but that it is a good way of hiding things for the command line.

**Comment by magicDGS** [comment]
Closing as abandoned - feel free to reopen or add a new issue if this is still a problem, @robmaz.
